style: github
# https://github.com/fobgochod/git-commit-message-format/blob/main/src/main/resources/messages/GitBundle.properties#L37
# https://github.com/garden-io/garden/tree/main/.chglog
# https://github.com/git-chglog/git-chglog
# https://github.com/quay/clair/tree/main/.chglog
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/guanguans/monorepo-builder-worker
options:
  commits:
    filters:
      Type:
        - build
        # - chore
        - ci
        - docs
        - feat
        - fix
        - perf
        - refactor
        - revert
        - style
        - test
  commit_groups:
    title_maps:
      # https://github.com/antfu/changelogithub/blob/main/src/config.ts
      # https://github.com/unjs/changelogen/blob/main/src/config.ts
      # https://gitmoji.dev/
      build: ğŸ“¦ Builds
      chore: ğŸ¡ Chores
      ci: ğŸ¤– Continuous Integrations
      docs: ğŸ“– Documents
      feat: âœ¨ Features # ğŸš€ Enhancements
      fix: ğŸ Bug Fixes
      perf: ğŸ Performance Improvements
      refactor: ğŸ’… Code Refactorings
      revert: âªï¸ Reverts
      style: ğŸ¨ Styles
      test: âœ… Tests
      examples: ğŸ€ Examples
      types: ğŸŒŠ Types
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
